# Generated by Django 3.0.1 on 2019-12-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='')),
                ('position_x', models.FloatField(default='')),
                ('position_y', models.FloatField(default='1')),
            ],
        ),
    ]
