# Generated by Django 3.0.1 on 2020-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_mapmarks_id_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmarks',
            name='id_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
