# Generated by Django 3.0.1 on 2020-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200607_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmarks',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mapmarks',
            name='image',
            field=models.ImageField(blank=True, default='media/Color_Bars_HD_16x9.tif', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mapmarks',
            name='position_y',
            field=models.FloatField(default=''),
        ),
    ]
