# Generated by Django 3.0.1 on 2020-06-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200624_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmarks',
            name='image',
            field=models.ImageField(blank=True, default='Color_Bars_HD_16x9.tif', upload_to=''),
        ),
    ]
