# Generated by Django 3.0.1 on 2020-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.TextField(default='NOT NULL')),
                ('comment', models.TextField(default='NOT NULL')),
            ],
        ),
    ]
