# Generated by Django 3.0.1 on 2020-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='id_mark',
            field=models.IntegerField(default='-1'),
        ),
    ]
