# Generated by Django 3.0 on 2020-06-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_comment_id_mark'),
        ('about', '0002_auto_20200606_1035'),
    ]

    operations = [
    ]
